#!/bin/bash
# QUICK START GUIDE - League of Legends Discord Bot

echo "=== LOL TRACKER BOT - QUICK START ==="
echo ""

# Step 1: Local Setup
echo "STEP 1: LOCAL SETUP (Run on your Mac)"
echo "========================================"
echo ""
echo "1. Clone the repo:"
echo "   cd ~/Desktop/python"
echo "   git clone <your-repo-url> lol-tracker"
echo "   cd lol-tracker"
echo ""
echo "2. Create virtual environment:"
echo "   python3.11 -m venv venv"
echo "   source venv/bin/activate"
echo ""
echo "3. Install dependencies:"
echo "   pip install -r requirements.txt"
echo ""
echo "4. Set up .env file:"
echo "   cp .env.example .env"
echo "   nano .env"
echo "   # Add your DISCORD_TOKEN and RIOT_API_KEY"
echo ""
echo "5. Edit config.json with your friends' summoner names"
echo ""
echo "6. Test locally:"
echo "   python main.py"
echo ""

# Step 2: Server Setup
echo "STEP 2: SERVER SETUP (Run on Oracle Cloud)"
echo "==========================================="
echo ""
echo "1. SSH into server:"
echo "   ssh -i ~/Desktop/python/ssh-key-2026-03-05.key opc@163.192.105.166"
echo ""
echo "2. Create project directory:"
echo "   sudo mkdir -p /opt/lol-tracker"
echo "   sudo chown opc:opc /opt/lol-tracker"
echo "   cd /opt/lol-tracker"
echo ""
echo "3. Clone from GitHub:"
echo "   git clone <your-repo-url> ."
echo ""
echo "4. Set up virtual environment:"
echo "   python3.11 -m venv venv"
echo "   source venv/bin/activate"
echo "   pip install -r requirements.txt"
echo ""
echo "5. Create .env on server:"
echo "   nano .env"
echo "   # Copy same content as your local .env"
echo ""
echo "6. Test:"
echo "   python main.py"
echo "   # Let it run 30 seconds, then Ctrl+C"
echo ""

# Step 3: Systemd Service
echo "STEP 3: SET UP SYSTEMD SERVICE (Keeps bot running 24/7)"
echo "========================================================"
echo ""
echo "1. Create service file:"
echo "   sudo nano /etc/systemd/system/lol-tracker.service"
echo ""
echo "2. Paste this content (from README.md):"
echo "   [Unit]"
echo "   Description=League of Legends Discord Bot Tracker"
echo "   After=network.target"
echo ""
echo "   [Service]"
echo "   Type=simple"
echo "   User=opc"
echo "   WorkingDirectory=/opt/lol-tracker"
echo "   Environment=\"PATH=/opt/lol-tracker/venv/bin\""
echo "   ExecStart=/opt/lol-tracker/venv/bin/python main.py"
echo "   Restart=always"
echo "   RestartSec=10"
echo "   StandardOutput=append:/opt/lol-tracker/bot.log"
echo "   StandardError=append:/opt/lol-tracker/bot.log"
echo ""
echo "   [Install]"
echo "   WantedBy=multi-user.target"
echo ""
echo "3. Enable and start:"
echo "   sudo systemctl daemon-reload"
echo "   sudo systemctl enable lol-tracker"
echo "   sudo systemctl start lol-tracker"
echo ""
echo "4. Check status:"
echo "   sudo systemctl status lol-tracker"
echo ""

# Common Commands
echo "COMMON COMMANDS"
echo "==============="
echo ""
echo "Check bot status:"
echo "  sudo systemctl status lol-tracker"
echo ""
echo "View logs:"
echo "  tail -f /opt/lol-tracker/bot.log"
echo ""
echo "Restart bot (if you push code updates to GitHub):"
echo "  sudo systemctl restart lol-tracker"
echo ""
echo "Stop bot:"
echo "  sudo systemctl stop lol-tracker"
echo ""
echo "Start bot:"
echo "  sudo systemctl start lol-tracker"
echo ""

echo "=== Setup Complete! ==="
